import { Brain, Trophy, Users, Zap } from "lucide-react";

export const featuresData = [
  {
    icon: Brain,
    title: "AI-Powered Questions",
    description:
      "Dynamic questions generated by advanced AI, ensuring fresh challenges every time you play.",
    iconProps: { size: 32, strokeWidth: 2 },
  },
  {
    icon: Zap,
    title: "Real-time Gameplay",
    description:
      "Experience instant feedback, live scoring, and seamless gameplay with real-time updates.",
    iconProps: { size: 32, strokeWidth: 2 },
  },
  {
    icon: Trophy,
    title: "Smart Scoring",
    description:
      "Earn points based on difficulty, speed, and accuracy. Build streaks for bonus rewards.",
    iconProps: { size: 32, strokeWidth: 2 },
  },
  {
    icon: Users,
    title: "Multiple Categories",
    description:
      "Test your knowledge across Science, History, Sports, Entertainment, and many more categories.",
    iconProps: { size: 32, strokeWidth: 2 },
  },
] as const;
