import { Brain, Trophy, Users, Zap } from "lucide-react";
import { Feature } from "./FeaturesSection";

export const featuresData: Feature[] = [
  {
    icon: Brain,
    title: "AI-Powered Questions",
    description:
      "Dynamic questions generated by advanced AI, ensuring fresh challenges every time you play.",
  },
  {
    icon: Zap,
    title: "Real-time Gameplay",
    description:
      "Experience instant feedback, live scoring, and seamless gameplay with real-time updates.",
  },
  {
    icon: Trophy,
    title: "Smart Scoring",
    description:
      "Earn points based on difficulty, speed, and accuracy. Build streaks for bonus rewards.",
  },
  {
    icon: Users,
    title: "Multiple Categories",
    description:
      "Test your knowledge across Science, History, Sports, Entertainment, and many more categories.",
  },
] as const;
